name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      - name: Install kcov dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libcurl4-openssl-dev libelf-dev libdw-dev cmake
      - name: Build and install kcov
        run: |
          git clone https://github.com/SimonKagstrom/kcov.git
          cd kcov
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - name: Check formatting
        run: |
          zig build fmt
      - name: Build
        run: |
          zig build
      - name: Run tests
        run: |
          zig build test
      - name: Generate coverage report
        run: |
          zig build cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: kcov-output/test/cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
