name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      - name: Install kcov
        run: |
          sudo apt install -y kcov
      - name: Check formatting
        run: |
          zig build fmt
      - name: Build
        run: |
          zig build
      - name: Run tests
        run: |
          zig build test
      - name: Generate coverage report
        run: |
          zig build cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
