name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      - name: Cache kcov build
        id: cache-kcov
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/kcov
          key: ${{ runner.os }}-kcov-1.0
      - name: Install kcov
        if: steps.cache-kcov.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y build-essential libcurl4-openssl-dev libelf-dev libdw-dev cmake
          git clone https://github.com/SimonKagstrom/kcov.git
          cd kcov
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
      - name: Check formatting
        run: |
          zig build fmt
      - name: Build
        run: |
          zig build
      - name: Run tests
        run: |
          zig build test
      - name: Generate coverage report
        run: |
          zig build cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: kcov-output/test/cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate docs site
        run: |
          zig build run -- doc
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: generated/
  deploy_pages:
    name: Deploy Docs Site
    needs:
      - build_and_test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
