name: CI Release Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mlugg/setup-zig@v2
      - name: Build x86_64-linux-gnu
        run: |
          zig build -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSafe --prefix x86_64-linux-gnu
      - name: Build aarch64-linux-gnu
        run: |
          zig build -Dtarget=aarch64-linux-gnu -Doptimize=ReleaseSafe --prefix aarch64-linux-gnu
      - name: Package
        run: |
          tar -czf "zmarkgen-${GITHUB_REF#refs/tags/}-x86_64-linux-gnu.tar.gz" -C x86_64-linux-gnu/bin zmarkgen
          tar -czf "zmarkgen-${GITHUB_REF#refs/tags/}-aarch64-linux-gnu.tar.gz" -C aarch64-linux-gnu/bin zmarkgen
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: "This release was automatically generated by CI from tag ${{ github.ref_name }}."
          files: |
            zmarkgen-${{ github.ref_name }}-x86_64-linux-gnu.tar.gz
            zmarkgen-${{ github.ref_name }}-aarch64-linux-gnu.tar.gz
